<?php
namespace app\controllers;

use app\services\HxapiService;
use yii\helpers\Json;
use yii\web\Controller;

class  HxpushController extends Controller {
    public $options;
  public function init()
  {
    $this->options=['client_id' =>'YXA67St1MHTPEeer-uM5B5Uv0Q',
        'client_secret' =>'YXA6eMPzUAg-pRfHTyxBq8jM4n3OIH0',
        'org_name' =>'1185170730178177',
        'app_name' =>'push-msg',
        'url',
        ];



      parent::init(); // TODO: Change the autogenerated stub
  }



    public function actionZc(){

        $model=new HxapiService($this->options);
//       $a= $model->getUser('yangr');
//        var_dump($a);

//        $res=$model->createUser('user','12300');

//        $res=$model->addFriend('yangr','user');

//        $model->deleteFriend('yangr','user');

//       $res= $model->createUsers(['username'=>'545','password'=>12311],
//            ['username'=>'2454','password'=>12315451]
//        );
//    $res=$model->isOnline('yangr');

//        $target_type='users';
//            $target=["user", "yangr"];
//                $content=[ "type" =>"txt","msg" => "hello from rest"];
//                $ext=null;
//   $a= $model->sendText(null,$target_type,$target,$content,$ext);
////        $a=$model->showFriends('1');
////        $a=$model->sendImage();

        $target_type='users';
            $target=["user", "yangr"];
            $filename='test.jpg';
                $content=[ "type" =>"img","msg" => [
                    'filename'=>$filename,
                    'size'=>[
                        'width'=>100,
                        'height'=>100
        ]
                ]];
                //上传
//                $a=$model->uploadFile(\Yii::getAlias('@webroot').'/images/'.$filename);
        //发送
        $a=$model->sendImage(\Yii::getAlias('@webroot').'/images/'.$filename,null,$target_type,$target,$filename);
       return json_encode($a);


//        var_dump($a);
    }
}