<?php
/**
 * Created by PhpStorm.
 * User: hj
 * Date: 6/3/17
 * Time: 4:30 PM
 */

return [
    // common
    'site/time-types' => [1, 2, 3, 4, 5, 6, 7],
    'site/upload' => [1, 2, 3, 4, 5, 6, 7],
    'site/admin-logout' => [1, 2, 3, 4, 5, 6, 7],
    'site/upload-delete' => [1, 2, 3, 4, 5, 6, 7],

    // recommend
    'mall/recommend-admin-index' => [1],
    'mall/recommend-disable-batch' => [1],
    'mall/recommend-delete-batch' => [1],
    'mall/recommend-delete' => [1],
    'mall/recommend-status-toggle' => [1],
    'mall/recommend-history' => [1],
    'mall/recommend-second-admin' => [1],
    'mall/recommend-by-sku' => [1],
    'mall/recommend-add' => [1],
    'mall/recommend-edit' => [1],
    'mall/recommend-sort' => [1],
//    'mall/recommend-click-record',
    'mall/recommend-add-supplier' => [6],
    'mall/recommend-edit-supplier' => [6],
    'mall/recommend-delete-supplier' => [6],
    'mall/recommend-delete-batch-supplier' => [6],
    'mall/recommend-admin-index-supplier' => [6],

    // category
    'mall/category-review' => [1],
    'mall/categories-admin' => [1, 6],
    'mall/category-status-toggle' => [1],
    'mall/category-disable-batch' => [1],
    'mall/category-enable-batch' => [1],
    'mall/category-list-admin' => [1, 6],
    'mall/categories-manage-admin' => [1, 6],
    'mall/category-add' => [1, 6],
    'mall/category-edit' => [1],
    'mall/category-offline-reason-reset' => [1],
    'mall/category-reason-reset' => [1],
    'mall/category-review-list' => [1],
//    'mall/category-brands' => [6],
    'mall/category-attrs' => [6],

    // brand
    'mall/brand-add' => [1, 6],
    'mall/brand-review' => [1],
    'mall/brand-edit' => [1],
    'mall/brand-offline-reason-reset' => [1],
    'mall/brand-reason-reset' => [1],
    'mall/brand-status-toggle' => [1],
    'mall/brand-disable-batch' => [1],
    'mall/brand-enable-batch' => [1],
    'mall/brand-review-list' => [1],
    'mall/brand-list-admin' => [1, 6],
    'mall/brand-application-add' => [6],
    'mall/brand-application-list-admin' => [1, 6],
    'mall/brand-application-review-list' => [1],
    'mall/brand-application-review-note-reset' => [1],
    'mall/brand-application-review' => [1],

    // logistics template
    'mall/logistics-template-add' => [6],
    'mall/logistics-template-edit' => [6],
    'mall/logistics-template-view' => [1, 6],
    'mall/logistics-templates-supplier' => [6],
    'mall/logistics-template-status-toggle' => [6],

    // goods attribute
    'mall/goods-attr-add' => [1],
    'mall/goods-attr-list-admin' => [1],

    // goods
    'mall/goods-add' => [6],
    'mall/goods-edit' => [1, 6],
    'mall/goods-edit-lhzz' => [1],
    'mall/goods-attrs-admin' => [6],
    'mall/goods-status-toggle' => [1, 6],
    'mall/goods-disable-batch' => [1, 6],
    'mall/goods-delete-batch' => [6],
    'mall/goods-enable-batch' => [1],
    'mall/goods-offline-reason-reset' => [1],
    'mall/goods-reason-reset' => [1],
    'mall/goods-list-admin' => [1, 6],
    'mall/goods-inventory-reset' => [6],
//    'mall/goods-images' => [1, 6],

    // supplier
    'mall/supplier-add' => [1],
    'mall/supplier-icon-reset' => [6],
    'mall/supplier-view-admin' => [1, 6],
    'mall/shop-data' => [1, 6],
    'mall/supplier-index-admin' => [6],
    'mall/check-role-get-identity' => [1],
    'mall/supplier-status-toggle' => [1],
    'mall/supplier-list' => [1],

    // mall
    'mall/index-admin' => [1],

    // user
    'mall/user-identity' => [1],
    'mall/user-add' => [1],
    'mall/reset-mobile' => [1],
    'mall/user-status-toggle' => [1],
    'mall/user-disable-batch' => [1],
    'mall/user-disable-remark-reset' => [1],
    'mall/user-enable-batch' => [1],
    'mall/user-view-lhzz' => [1],
    'mall/reset-user-status-logs' => [1],
    'mall/user-list' => [1],
    'mall/reset-mobile-logs' => [1],
    
    // lhzz
    'mall/index-admin-lhzz' => [1],

    // style and series
    'mall/categories-have-style-series' => [1],
    'mall/categories-style-series-reset' => [1],

    // houzi
    'order/getsupplierorderdetails' => [1,6],
    'order/expressupdate' => [6],
    'order/supplierdelivery' => [6],
    'order/getexpress' => [1,6],
    'order/getplatformdetail' => [1,6],
    'order/getorderdetailsall' => [1,6],
    'order/platformhandlesubmit' => [1],
    'order/find-order-list' => [1,6],
    'order/find-supplier-order-list' => [6],
    'order/find-unusual-list' => [6],
    'order/find-unusual-list-lhzz' => [1],
    'order/get-comment' => [1,6],
    'order/comment-reply' => [6],
    'order/supplier-after-sale-handle' => [6],
    'order/refund-handle' => [6],
    'order/supplier-delete-comment' => [1,6],
    'order/delete-comment-list' => [1,6],
    'order/delete-comment-details' => [1,6],
    'order/goods-view' => [1,6],
    'distribution/getdistributionlist' => [1],
    'distribution/getdistributiondetail' => [1],
    'distribution/searchmore' => [1],
    'distribution/add-profit' => [1],
    'distribution/add-remarks' => [1],
    'distribution/correlate-order' => [1],
    'order/refund-handle' => [6],
    'order/find-refund-detail' => [6],
    'order/supplier-after-sale-handle' => [6],
    'order/after-sale-supplier-send-man' => [6],
    'order/after-sale-supplier-confirm' => [6],
    'order/after-sale-delivery' => [1,6],
    'order/find-shipping-cart-list' => [1,6],

    // yr
    'effect/effect-list'=> [1],
    'effect/effect-view'=>[1],
    'supplieraccount/account-list'=>[1],
    'supplieraccount/account-view'=>[1],
    'supplieraccount/apply-freeze'=>[1],
    'supplieraccount/freeze-money'=>[1],
    'supplieraccount/freeze-list'=>[1],
    'supplieraccount/account-thaw'=>[1],
    'supplieraccount/cashed-list'=>[1],
    'supplieraccount/cashed-view'=>[1],
    'supplieraccount/category'=>[1],
    'supplier-cash/cash-index'=>[1],
    'supplier-cash/order-list-today'=>[1],
    'supplier-cash/cash-list-today'=>[1],
    'supplier-cash/cash-action-detail'=>[1],
    'supplier-cash/cash-deal'=>[1],
    'supplier-cash/mall-view'=>[6],
    'supplier-cash/get-cash-list'=>[6],
    'supplier-cash/get-cash'=>[1,6],
    'withdrawals/find-balance'=>[6],
    'withdrawals/check-isset-pay-pwd'=>[6],
    'withdrawals/send-pay-code'=>[6],
    'withdrawals/set-pay-pwd'=>[6],
    'withdrawals/find-supplier-balance'=>[6],
    'withdrawals/supplier-withdrawals-apply'=>[6],
    'withdrawals/find-supplier-freeze-list'=>[6],
    'withdrawals/supplier-access-detail'=>[6],
    'withdrawals/find-supplier-access-detail-list'=>[6],
    'withdrawals/check-cash-money'=>[1,6],
    'withdrawals/check-supplier-pay-pwd'=>[1,6],
    'withdrawals/set-bank-card'=>[6],
    'withdrawals/find-bank-card'=>[6],
    'withdrawals/find-balance'=>[6],
    'supplieraccount/owner-account-list'=>[1],
    'supplieraccount/owner-account-detail'=>[1],
    'supplieraccount/owner-freeze-money'=>[1],
    'supplieraccount/owner-apply-freeze'=>[1],
    'supplieraccount/owner-freeze-list'=>[1],
    'supplieraccount/owner-freeze-taw'=>[1],
    'supplier-cash/owner-cash-index'=>[1],
    'supplier-cash/owner-cashed-list'=>[1],
    'supplier-cash/owner-cashed-detail'=>[1],
    'supplier-cash/owner-do-cash-deal'=>[1],

    // wei
    'quote/labor-cost-list' => [1],
    'quote/labor-cost-edit-list' => [1],
    'quote/labor-cost-edit' => [1],
    'quote/project-norm-list' => [1],
    'quote/project-norm-edit-list' => [1],
    'quote/project-norm-edit' => [1],
    'quote/project-norm-woodwork-list' => [1],
    'quote/project-norm-woodwork-edit' => [1],
    'quote/coefficient-list' => [1],
    'quote/coefficient-add' => [1],
    'quote/plot-list' => [1],
    'quote/labor-list' => [1],
    'quote/series-and-style' => [1],
    'quote/plot-add' => [1],
    'quote/plot-edit-view' => [1],
    'quote/plot-edit' => [1],
    'quote/plot-del' => [1],
    'quote/assort-goods' => [1],
    'quote/assort-goods-list' => [1],
    'quote/assort-goods-add' => [1],
    'quote/homepage-list' => [1],
    'quote/homepage-sort' => [1],
    'quote/homepage-district' => [1],
    'quote/homepage-toponymy' => [1],
    'quote/homepage-street' => [1],
    'quote/homepage-case' => [1],
    'quote/homepage-add' => [1],
    'quote/homepage-status' => [1],
    'quote/homepage-edit' => [1],
    'quote/homepage-delete' => [1],
    'quote/apartment-area-list' => [1],
    'quote/apartment-area' => [1],
    'quote/decoration-list' => [1],
    'quote/decoration-add-classify' => [1],
    'quote/house-type-list' => [1],
    'quote/decoration-message-list' => [1],
    'quote/decoration-add' => [1],
    'quote/decoration-del' => [1],
    'quote/decoration-edit-list' => [1],
    'quote/decoration-edit' => [1],
    'quote/commonality-list' => [1],
    'quote/commonality-title' => [1],
    'quote/commonality-title-add' => [1],
    'quote/commonality-title-two-add' => [1],
    'quote/commonality-else-list' => [1],
    'quote/commonality-else-edit' => [1],
    'quote/goods-management-list' => [1],
    'quote/goods-management-add' => [1],
    'quote/sku-fefer' => [1],
    'mall/series-list' => [1],
    'mall/series-time-sort' => [1],
    'mall/series-add' => [1],
    'mall/series-edit' => [1],
    'mall/series-status' => [1],
    'mall/style-list' => [1],
    'mall/style-time-sort' => [1],
    'mall/style-add' => [1],
    'mall/style-edit' => [1],
    'mall/style-status' => [1],
    'worker-management/homepage-list' => [1],
    'worker-management/worker-type-list' => [1],
    'worker-management/worker-type-add' => [1],
    'worker-management/worker-type-edit' => [],
    'worker-management/worker-list' => [1],
    'worker-management/worker-phone' => [1],
    'worker-management/worker-add' => [1],
    'worker-management/worker-order-list' => [1],
    'worker-management/workerOrderStatus' => [1],
];