<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/5/8 0008
 * Time: 下午 14:34
 */
namespace app\models;

use yii\data\Pagination;
use yii\db\ActiveRecord;
use yii\db\Query;

class Effect extends ActiveRecord
{
    const  SUP_BANK_CARD='effect';
    const TYPE_STATUS_YES = 1;
    const TYPE_STATUS_NO = 0;
    const STATUS_STAIRWAY_YES = 1;
    const PAGE_SIZE_DEFAULT = 12;
    const FIELDS_EXTRA = [];
    const FIELDS_VIEW_ADMIN_MODEL = [
          'id',
          'bedroom',
          'sittingRoom_diningRoom',
          'toilet',
          'kitchen',
          'window',
          'area',
          'high',
          'province',
          'province_code',
          'city',
          'city_code',
          'district',
          'district_code',
          'toponymy',
          'street',
          'particulars',
          'stairway',
          'add_time',
          'house_image',
          'type',
        ];
    /**
     * @return string 返回该AR类关联的数据表名
     */
    public static function tableName()
    {
        return 'effect';
    }

    public function rules()
    {
        return [
            [['bedroom','sittingRoom_diningRoom','toilet','kitchen','window','area','high','province','province_code','city','city_code','district','district_code', 'toponymy','street','particulars','stairway','house_image','type'], 'required'],
            [['province', 'city','district','toponymy','street','particulars'],'string'],
            [['bedroom','sittingRoom_diningRoom','toilet','kitchen','window','area','high'],'number']
        ];
    }

    /**
     * @param string $search
     * @return array|ActiveRecord[]
     */
    public static function districtSearch($search = '花好月圆')
    {
        $detail = self::find()
            ->asArray()
            ->where(['like','toponymy',$search])
            ->all();
        return $detail;
    }

    public function geteffectdata($effect_id){

        $query=new Query();

        $array= $query->from('effect As e')->select('e.toponymy,e.province,e.city,e.particulars,e.high,e.window,t.style,s.series')->leftJoin('series As s','s.id = e.series_id')->leftJoin('style As t','t.id = e.style_id')->where(['e.id'=>$effect_id])->one();
        $array1=(new Query())->from('effect_earnst')->select('phone,name,create_time,earnest,remark')->where(['effect_id'=>$effect_id])->one();
        if($array){
            $array['phone']=$array1['phone'];
            $array['create_time']=$array1['create_time'];
            $array['earnest']=sprintf('%.2f',(float)$array1['earnest']*0.01);
            $array['name']=$array1['name'];
            $array['remark']=$array1['remark'];


            return $array;
        }

        return null;
    }
    public function beforeSave($insert)
    {
        if($insert){
            $this->add_time=time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @param $arr
     * @return array|null|ActiveRecord
     */
    public static function conditionQuery($arr)
    {
        $basis_condition = [];
        $basis_condition ['room'] = $arr['room'];
        $basis_condition ['hall'] = $arr['hall'];
        $basis_condition ['toilet'] = $arr['toilet'];
        $basis_condition ['kitchen'] = $arr['kitchen'];
        $basis_condition ['area'] = $arr['area'];
        $basis_condition ['high'] = $arr['high'];
        $basis_condition ['window'] = $arr['window'];

        $effect = self::find()->where([
            'and','room'   => $basis_condition ['room'],
            'hall'         => $basis_condition ['hall'],
            'toilet'       => $basis_condition ['toilet'],
            'kitchen'      => $basis_condition ['kitchen'],
            'high'         => $basis_condition ['high'],
            'window'       => $basis_condition ['window']])
            ->one();
        return $effect;
    }




    /**
     * toponymy find all
     * @return string
     */
    public static function conditionFind($post)
    {
        $effect = self::find()
            ->select('effect.toponymy,effect.add_time,effect.district')
            ->groupBy('toponymy')
            ->where(['like','toponymy' => $post])
            ->asArray()
            ->all();
        $list = [];
        foreach ($effect as $one_model)
        {
            $one_model['add_time'] = date('Y-m-d H:i',$one_model['add_time']);
            $list [] = $one_model;
        }
        return $list;
    }

    public static function pagination($where,$page = 1, $size = self::PAGE_SIZE_DEFAULT)
    {
        $offset = ($page - 1) * $size;
        $effectList = self::find()
            ->select('id,toponymy,add_time,district,street')
            ->where($where)
            ->groupBy('toponymy')
            ->orderBy(['add_time' => SORT_ASC])
            ->offset($offset)
            ->limit($size)
            ->asArray()
            ->all();

        foreach ($effectList as &$effect) {

            if(isset($effect['add_time'])){
                $effect['add_time']=date('Y-m-d H:i', $effect['add_time']);
            }

        }

        return [
            'total' => (int)self::find()->where($where)->asArray()->count(),
            'page'=>$page,
            'size'=>$size,
            'details' => $effectList
        ];
    }

    public function plotAdd($bedroom,$sittingRoom_diningRoom,$toilet,$kitchen,$window,$area,$high,$province,$province_code,$city,$city_code,$district,$district_code,$toponymy,$street,$particulars,$stairway,$add_time,$house_image,$type)
    {
        $res = \Yii::$app->db->createCommand()->insert(self::SUP_BANK_CARD,[
            'bedroom'       => $bedroom,
            'sittingRoom_diningRoom' => $sittingRoom_diningRoom,
            'toilet'        => $toilet,
            'kitchen'       => $kitchen,
            'window'        => $window,
            'area'          => $area,
            'high'          => $high,
            'province'      => $province,
            'province_code' => $province_code,
            'city'          => $city,
            'city_code'     => $city_code,
            'district'      => $district,
            'district_code' => $district_code,
            'toponymy'      => $toponymy,
            'street'        => $street,
            'particulars'   => $particulars,
            'stairway'      => $stairway,
            'add_time'      => $add_time,
            'house_image'   => $house_image,
            'type'          => $type,
        ])->execute();

        return $res;
    }

    public function plotEdit($id,$bedroom,$sittingRoom_diningRoom,$toilet,$kitchen,$window,$area,$high,$province,$province_code,$city,$city_code,$district,$district_code,$toponymy,$street,$particulars,$stairway,$add_time,$house_image,$type)
    {
        $res = \Yii::$app->db->createCommand()->update(self::SUP_BANK_CARD,[
            'bedroom'       => $bedroom,
            'sittingRoom_diningRoom' => $sittingRoom_diningRoom,
            'toilet'        => $toilet,
            'kitchen'       => $kitchen,
            'window'        => $window,
            'area'          => $area,
            'high'          => $high,
            'province'      => $province,
            'province_code' => $province_code,
            'city'          => $city,
            'city_code'     => $city_code,
            'district'      => $district,
            'district_code' => $district_code,
            'toponymy'      => $toponymy,
            'street'        => $street,
            'particulars'   => $particulars,
            'stairway'      => $stairway,
            'add_time'      => $add_time,
            'house_image'   => $house_image,
            'type'          => $type,
        ],'id='. $id)->execute();

        return $res;
    }

    public static function condition($street,$toponymy,$district)
    {
        return self::find()
            ->asArray()
            ->where(['and',['street'=>$street],['toponymy'=>$toponymy],['district'=>$district]])
            ->all();
    }

}