<?php

namespace app\models;

use app\services\StringService;
use Yii;

/**
 * This is the model class for table "effect_earnst".
 *
 * @property string $id
 * @property string $phone
 * @property string $name
 * @property string $earnest
 * @property string $remark
 * @property string $create_time
 * @property string $effect_id
 */
class EffectEarnst extends \yii\db\ActiveRecord
{
    const INSET_EARNST = 89;
    const PAGE_SIZE_DEFAULT = 10;
    const FIELDS_EXTRA = [];
    const FIELDS_ADMIN = [
        'create_time',
        'name',
        'phone',
        'earnest',
        'remark',

    ];
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'effect_earnst';

    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['phone', 'name'], 'required'],
            [['remark'], 'string'],
//            [['phone'], 'integerPattern'=>'/^[1]{3,5,7,8}\d{9}$/'],
            [['name'], 'string', 'min' => 1, 'max' => 8],
            [['create_time'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function beforeSave($insert)
    {

        if ($insert) {
            $this->earnest = self::INSET_EARNST;
            $this->create_time = date('Ymd',time());
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }


    public static function pagination($where = [], $select = [], $page = 1, $size = self::PAGE_SIZE_DEFAULT, $orderBy = 'id DESC')
    {
        $select = array_diff($select, self::FIELDS_EXTRA);

        $offset = ($page - 1) * $size;
        $effectList = self::find()
            ->select($select)
            ->where($where)
            ->orderBy($orderBy)
            ->offset($offset)
            ->limit($size)
            ->asArray()
            ->all();

        foreach ($effectList as &$effect) {
            if (isset($effect['create_time'])) {
                $effect['create_time'] = substr($effect['create_time'], 0, 4) . '-'
                    . substr($effect['create_time'], 4, 2) . '-'
                    . substr($effect['create_time'], 6);
            }
            if(isset($effect['phone'])){

                $effect['phone'];
            }

        }

        return [
            'total' => (int)self::find()->where($where)->asArray()->count(),
            'details' => $effectList
        ];
    }





}